---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lVQkg5SmFBZU5wZGlpblVmNTdsMk1zL3FBWUZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZZMkV0YjNCbGJtWjFibU4wYVc5dUxYZGxZbWh2YjJzdGMyVnlkbWxqWlRBZQpGdzB5TWpBM01EUXdPREF5TWpSYUZ3MHpNakEzTURFd09EQXlNalJhTUNveEtEQW1CZ05WQkFNTUgyTmhMVzl3ClpXNW1kVzVqZEdsdmJpMTNaV0pvYjI5ckxYTmxjblpwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMXBqWSt5eG1LWEJCYm9MUjJEODM2b0tIaXgyQ3l1YkdvdXV0NkFxNGp0bWlTV2FYYwpxSUJKemFIczBOYjNaVmJQMVM3VXgrOUNjcUM5elpqTHVZNUVwSlRnOVVPbkJaVVhTNXdjTE5oMlo1WWpaaDZ0CnluTmxNaFlnSDlMRHpSNWtHTDJxRHEwWnBqSm12T245bXFtbjdFUm5QUFk2cHdlL1hXc1RVWGFLV2NOUEhmOVMKeTljQjA5MUlCMitjazM4Q04weXN2Wm5BeE9NclFBU1dqZ29Rbk14bkViUWs2d2dXSzh5aG5ielgydmJLUXVyTwp2dHZMdDh2Q3N2WFdtdlpwV3NXZ3BnMCtiUDh2WUlKbmNtT09QdFI4cExIUC9QRkpFeElpazhGV29pOU1wc1gvCllEQWJrenZnRURYdGZ5SEVXWGRlN0Ura1NWaXJ2OUQ2ZEtkYkFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVG8KRWp1S1pWdHc4QjZPRlNYWnczV09VTzN1WHpBZkJnTlZIU01FR0RBV2dCVG9FanVLWlZ0dzhCNk9GU1hadzNXTwpVTzN1WHpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNTk0M3JzZGl3CkJGOXB3RmJqZXg4ZTNJVWlhTlQva2tOdmhuaG5HWXJFR2NCRGdKb1Rhc2YxYzlHZ005VVB2TFhyUWZpR3VCc0cKNU5OejdIcUZyZ3V4T0pFdk5Ga3B1Vks5YzcycXdxNWRpV2pEa0R4R0FMTXRPY0IwTTVpcXVZYUlmdkhhUzBrNApSYStmSDlyR0hSRUREME1BU0Vqd0EyVGVMVUpxVWJBMzh0MTY0cEZQUzl6WUR0VlRaNzM5bDRFNnNyNW1GRzJWCjJZNmpGZ1YwRHJzSS90VmVoT2pFbHMyc1hISXQ3eDNHZzlCVXNhZ0NJaExFQjJWQVczVFZCVVZCTGpBY25ZMmwKMTBxMUhhQ2hLd2lqM01lUWVzTFEvbTdhLytNTU9ob3dRMExJSENkRE5nOTNvZWVtM3FsZmx3bFFLNzlzSitTRQpRbG5BSlVBam1rZ3IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
#      service:
#        name: webhook-service
#        namespace: openfunction
#        path: /mutate-core-openfunction-io-v1beta1-function
      url: "https://172.31.73.52:9443/mutate-core-openfunction-io-v1beta1-function"
    failurePolicy: Fail
    name: mfunctions.of.io
    rules:
      - apiGroups:
          - core.openfunction.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - functions
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lVQkg5SmFBZU5wZGlpblVmNTdsMk1zL3FBWUZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZZMkV0YjNCbGJtWjFibU4wYVc5dUxYZGxZbWh2YjJzdGMyVnlkbWxqWlRBZQpGdzB5TWpBM01EUXdPREF5TWpSYUZ3MHpNakEzTURFd09EQXlNalJhTUNveEtEQW1CZ05WQkFNTUgyTmhMVzl3ClpXNW1kVzVqZEdsdmJpMTNaV0pvYjI5ckxYTmxjblpwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMXBqWSt5eG1LWEJCYm9MUjJEODM2b0tIaXgyQ3l1YkdvdXV0NkFxNGp0bWlTV2FYYwpxSUJKemFIczBOYjNaVmJQMVM3VXgrOUNjcUM5elpqTHVZNUVwSlRnOVVPbkJaVVhTNXdjTE5oMlo1WWpaaDZ0CnluTmxNaFlnSDlMRHpSNWtHTDJxRHEwWnBqSm12T245bXFtbjdFUm5QUFk2cHdlL1hXc1RVWGFLV2NOUEhmOVMKeTljQjA5MUlCMitjazM4Q04weXN2Wm5BeE9NclFBU1dqZ29Rbk14bkViUWs2d2dXSzh5aG5ielgydmJLUXVyTwp2dHZMdDh2Q3N2WFdtdlpwV3NXZ3BnMCtiUDh2WUlKbmNtT09QdFI4cExIUC9QRkpFeElpazhGV29pOU1wc1gvCllEQWJrenZnRURYdGZ5SEVXWGRlN0Ura1NWaXJ2OUQ2ZEtkYkFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVG8KRWp1S1pWdHc4QjZPRlNYWnczV09VTzN1WHpBZkJnTlZIU01FR0RBV2dCVG9FanVLWlZ0dzhCNk9GU1hadzNXTwpVTzN1WHpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNTk0M3JzZGl3CkJGOXB3RmJqZXg4ZTNJVWlhTlQva2tOdmhuaG5HWXJFR2NCRGdKb1Rhc2YxYzlHZ005VVB2TFhyUWZpR3VCc0cKNU5OejdIcUZyZ3V4T0pFdk5Ga3B1Vks5YzcycXdxNWRpV2pEa0R4R0FMTXRPY0IwTTVpcXVZYUlmdkhhUzBrNApSYStmSDlyR0hSRUREME1BU0Vqd0EyVGVMVUpxVWJBMzh0MTY0cEZQUzl6WUR0VlRaNzM5bDRFNnNyNW1GRzJWCjJZNmpGZ1YwRHJzSS90VmVoT2pFbHMyc1hISXQ3eDNHZzlCVXNhZ0NJaExFQjJWQVczVFZCVVZCTGpBY25ZMmwKMTBxMUhhQ2hLd2lqM01lUWVzTFEvbTdhLytNTU9ob3dRMExJSENkRE5nOTNvZWVtM3FsZmx3bFFLNzlzSitTRQpRbG5BSlVBam1rZ3IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
#      service:
#        name: webhook-service
#        namespace: openfunction
#        path: /mutate-core-openfunction-io-v1beta1-serving
      url: "https://172.31.73.52:9443/mutate-core-openfunction-io-v1beta1-serving"
    failurePolicy: Fail
    name: mservings.of.io
    rules:
      - apiGroups:
          - core.openfunction.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servings
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lVQkg5SmFBZU5wZGlpblVmNTdsMk1zL3FBWUZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZZMkV0YjNCbGJtWjFibU4wYVc5dUxYZGxZbWh2YjJzdGMyVnlkbWxqWlRBZQpGdzB5TWpBM01EUXdPREF5TWpSYUZ3MHpNakEzTURFd09EQXlNalJhTUNveEtEQW1CZ05WQkFNTUgyTmhMVzl3ClpXNW1kVzVqZEdsdmJpMTNaV0pvYjI5ckxYTmxjblpwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMXBqWSt5eG1LWEJCYm9MUjJEODM2b0tIaXgyQ3l1YkdvdXV0NkFxNGp0bWlTV2FYYwpxSUJKemFIczBOYjNaVmJQMVM3VXgrOUNjcUM5elpqTHVZNUVwSlRnOVVPbkJaVVhTNXdjTE5oMlo1WWpaaDZ0CnluTmxNaFlnSDlMRHpSNWtHTDJxRHEwWnBqSm12T245bXFtbjdFUm5QUFk2cHdlL1hXc1RVWGFLV2NOUEhmOVMKeTljQjA5MUlCMitjazM4Q04weXN2Wm5BeE9NclFBU1dqZ29Rbk14bkViUWs2d2dXSzh5aG5ielgydmJLUXVyTwp2dHZMdDh2Q3N2WFdtdlpwV3NXZ3BnMCtiUDh2WUlKbmNtT09QdFI4cExIUC9QRkpFeElpazhGV29pOU1wc1gvCllEQWJrenZnRURYdGZ5SEVXWGRlN0Ura1NWaXJ2OUQ2ZEtkYkFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVG8KRWp1S1pWdHc4QjZPRlNYWnczV09VTzN1WHpBZkJnTlZIU01FR0RBV2dCVG9FanVLWlZ0dzhCNk9GU1hadzNXTwpVTzN1WHpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNTk0M3JzZGl3CkJGOXB3RmJqZXg4ZTNJVWlhTlQva2tOdmhuaG5HWXJFR2NCRGdKb1Rhc2YxYzlHZ005VVB2TFhyUWZpR3VCc0cKNU5OejdIcUZyZ3V4T0pFdk5Ga3B1Vks5YzcycXdxNWRpV2pEa0R4R0FMTXRPY0IwTTVpcXVZYUlmdkhhUzBrNApSYStmSDlyR0hSRUREME1BU0Vqd0EyVGVMVUpxVWJBMzh0MTY0cEZQUzl6WUR0VlRaNzM5bDRFNnNyNW1GRzJWCjJZNmpGZ1YwRHJzSS90VmVoT2pFbHMyc1hISXQ3eDNHZzlCVXNhZ0NJaExFQjJWQVczVFZCVVZCTGpBY25ZMmwKMTBxMUhhQ2hLd2lqM01lUWVzTFEvbTdhLytNTU9ob3dRMExJSENkRE5nOTNvZWVtM3FsZmx3bFFLNzlzSitTRQpRbG5BSlVBam1rZ3IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
#      service:
#        name: webhook-service
#        namespace: system
#        path: /mutate-networking-openfunction-io-v1alpha1-gateway
      url: "https://172.31.73.52:9443/mutate-networking-openfunction-io-v1alpha1-gateway"
    failurePolicy: Fail
    name: mgateway.of.io
    rules:
      - apiGroups:
          - networking.openfunction.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - gateways
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lVQkg5SmFBZU5wZGlpblVmNTdsMk1zL3FBWUZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZZMkV0YjNCbGJtWjFibU4wYVc5dUxYZGxZbWh2YjJzdGMyVnlkbWxqWlRBZQpGdzB5TWpBM01EUXdPREF5TWpSYUZ3MHpNakEzTURFd09EQXlNalJhTUNveEtEQW1CZ05WQkFNTUgyTmhMVzl3ClpXNW1kVzVqZEdsdmJpMTNaV0pvYjI5ckxYTmxjblpwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMXBqWSt5eG1LWEJCYm9MUjJEODM2b0tIaXgyQ3l1YkdvdXV0NkFxNGp0bWlTV2FYYwpxSUJKemFIczBOYjNaVmJQMVM3VXgrOUNjcUM5elpqTHVZNUVwSlRnOVVPbkJaVVhTNXdjTE5oMlo1WWpaaDZ0CnluTmxNaFlnSDlMRHpSNWtHTDJxRHEwWnBqSm12T245bXFtbjdFUm5QUFk2cHdlL1hXc1RVWGFLV2NOUEhmOVMKeTljQjA5MUlCMitjazM4Q04weXN2Wm5BeE9NclFBU1dqZ29Rbk14bkViUWs2d2dXSzh5aG5ielgydmJLUXVyTwp2dHZMdDh2Q3N2WFdtdlpwV3NXZ3BnMCtiUDh2WUlKbmNtT09QdFI4cExIUC9QRkpFeElpazhGV29pOU1wc1gvCllEQWJrenZnRURYdGZ5SEVXWGRlN0Ura1NWaXJ2OUQ2ZEtkYkFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVG8KRWp1S1pWdHc4QjZPRlNYWnczV09VTzN1WHpBZkJnTlZIU01FR0RBV2dCVG9FanVLWlZ0dzhCNk9GU1hadzNXTwpVTzN1WHpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNTk0M3JzZGl3CkJGOXB3RmJqZXg4ZTNJVWlhTlQva2tOdmhuaG5HWXJFR2NCRGdKb1Rhc2YxYzlHZ005VVB2TFhyUWZpR3VCc0cKNU5OejdIcUZyZ3V4T0pFdk5Ga3B1Vks5YzcycXdxNWRpV2pEa0R4R0FMTXRPY0IwTTVpcXVZYUlmdkhhUzBrNApSYStmSDlyR0hSRUREME1BU0Vqd0EyVGVMVUpxVWJBMzh0MTY0cEZQUzl6WUR0VlRaNzM5bDRFNnNyNW1GRzJWCjJZNmpGZ1YwRHJzSS90VmVoT2pFbHMyc1hISXQ3eDNHZzlCVXNhZ0NJaExFQjJWQVczVFZCVVZCTGpBY25ZMmwKMTBxMUhhQ2hLd2lqM01lUWVzTFEvbTdhLytNTU9ob3dRMExJSENkRE5nOTNvZWVtM3FsZmx3bFFLNzlzSitTRQpRbG5BSlVBam1rZ3IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
#      service:
#        name: webhook-service
#        namespace: openfunction
#        path: /validate-core-openfunction-io-v1beta1-function
      url: "https://172.31.73.52:9443/validate-core-openfunction-io-v1beta1-function"
    failurePolicy: Fail
    name: vfunctions.of.io
    rules:
      - apiGroups:
          - core.openfunction.io
        apiVersions:
          - v1beta1
        operations:
          - CREATE
          - UPDATE
        resources:
          - functions
    sideEffects: None
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lVQkg5SmFBZU5wZGlpblVmNTdsMk1zL3FBWUZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZZMkV0YjNCbGJtWjFibU4wYVc5dUxYZGxZbWh2YjJzdGMyVnlkbWxqWlRBZQpGdzB5TWpBM01EUXdPREF5TWpSYUZ3MHpNakEzTURFd09EQXlNalJhTUNveEtEQW1CZ05WQkFNTUgyTmhMVzl3ClpXNW1kVzVqZEdsdmJpMTNaV0pvYjI5ckxYTmxjblpwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMXBqWSt5eG1LWEJCYm9MUjJEODM2b0tIaXgyQ3l1YkdvdXV0NkFxNGp0bWlTV2FYYwpxSUJKemFIczBOYjNaVmJQMVM3VXgrOUNjcUM5elpqTHVZNUVwSlRnOVVPbkJaVVhTNXdjTE5oMlo1WWpaaDZ0CnluTmxNaFlnSDlMRHpSNWtHTDJxRHEwWnBqSm12T245bXFtbjdFUm5QUFk2cHdlL1hXc1RVWGFLV2NOUEhmOVMKeTljQjA5MUlCMitjazM4Q04weXN2Wm5BeE9NclFBU1dqZ29Rbk14bkViUWs2d2dXSzh5aG5ielgydmJLUXVyTwp2dHZMdDh2Q3N2WFdtdlpwV3NXZ3BnMCtiUDh2WUlKbmNtT09QdFI4cExIUC9QRkpFeElpazhGV29pOU1wc1gvCllEQWJrenZnRURYdGZ5SEVXWGRlN0Ura1NWaXJ2OUQ2ZEtkYkFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVG8KRWp1S1pWdHc4QjZPRlNYWnczV09VTzN1WHpBZkJnTlZIU01FR0RBV2dCVG9FanVLWlZ0dzhCNk9GU1hadzNXTwpVTzN1WHpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNTk0M3JzZGl3CkJGOXB3RmJqZXg4ZTNJVWlhTlQva2tOdmhuaG5HWXJFR2NCRGdKb1Rhc2YxYzlHZ005VVB2TFhyUWZpR3VCc0cKNU5OejdIcUZyZ3V4T0pFdk5Ga3B1Vks5YzcycXdxNWRpV2pEa0R4R0FMTXRPY0IwTTVpcXVZYUlmdkhhUzBrNApSYStmSDlyR0hSRUREME1BU0Vqd0EyVGVMVUpxVWJBMzh0MTY0cEZQUzl6WUR0VlRaNzM5bDRFNnNyNW1GRzJWCjJZNmpGZ1YwRHJzSS90VmVoT2pFbHMyc1hISXQ3eDNHZzlCVXNhZ0NJaExFQjJWQVczVFZCVVZCTGpBY25ZMmwKMTBxMUhhQ2hLd2lqM01lUWVzTFEvbTdhLytNTU9ob3dRMExJSENkRE5nOTNvZWVtM3FsZmx3bFFLNzlzSitTRQpRbG5BSlVBam1rZ3IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
#      service:
#        name: webhook-service
#        namespace: system
#        path: /validate-networking-openfunction-io-v1alpha1-gateway
      url: "https://172.31.73.52:9443/validate-networking-openfunction-io-v1alpha1-gateway"
    failurePolicy: Fail
    name: vgateway.of.io
    rules:
      - apiGroups:
          - networking.openfunction.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - gateways
    sideEffects: None