# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: servings.core.openfunction.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUROVENDQWgyZ0F3SUJBZ0lVQkg5SmFBZU5wZGlpblVmNTdsMk1zL3FBWUZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tqRW9NQ1lHQTFVRUF3d2ZZMkV0YjNCbGJtWjFibU4wYVc5dUxYZGxZbWh2YjJzdGMyVnlkbWxqWlRBZQpGdzB5TWpBM01EUXdPREF5TWpSYUZ3MHpNakEzTURFd09EQXlNalJhTUNveEtEQW1CZ05WQkFNTUgyTmhMVzl3ClpXNW1kVzVqZEdsdmJpMTNaV0pvYjI5ckxYTmxjblpwWTJVd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMXBqWSt5eG1LWEJCYm9MUjJEODM2b0tIaXgyQ3l1YkdvdXV0NkFxNGp0bWlTV2FYYwpxSUJKemFIczBOYjNaVmJQMVM3VXgrOUNjcUM5elpqTHVZNUVwSlRnOVVPbkJaVVhTNXdjTE5oMlo1WWpaaDZ0CnluTmxNaFlnSDlMRHpSNWtHTDJxRHEwWnBqSm12T245bXFtbjdFUm5QUFk2cHdlL1hXc1RVWGFLV2NOUEhmOVMKeTljQjA5MUlCMitjazM4Q04weXN2Wm5BeE9NclFBU1dqZ29Rbk14bkViUWs2d2dXSzh5aG5ielgydmJLUXVyTwp2dHZMdDh2Q3N2WFdtdlpwV3NXZ3BnMCtiUDh2WUlKbmNtT09QdFI4cExIUC9QRkpFeElpazhGV29pOU1wc1gvCllEQWJrenZnRURYdGZ5SEVXWGRlN0Ura1NWaXJ2OUQ2ZEtkYkFnTUJBQUdqVXpCUk1CMEdBMVVkRGdRV0JCVG8KRWp1S1pWdHc4QjZPRlNYWnczV09VTzN1WHpBZkJnTlZIU01FR0RBV2dCVG9FanVLWlZ0dzhCNk9GU1hadzNXTwpVTzN1WHpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBNTk0M3JzZGl3CkJGOXB3RmJqZXg4ZTNJVWlhTlQva2tOdmhuaG5HWXJFR2NCRGdKb1Rhc2YxYzlHZ005VVB2TFhyUWZpR3VCc0cKNU5OejdIcUZyZ3V4T0pFdk5Ga3B1Vks5YzcycXdxNWRpV2pEa0R4R0FMTXRPY0IwTTVpcXVZYUlmdkhhUzBrNApSYStmSDlyR0hSRUREME1BU0Vqd0EyVGVMVUpxVWJBMzh0MTY0cEZQUzl6WUR0VlRaNzM5bDRFNnNyNW1GRzJWCjJZNmpGZ1YwRHJzSS90VmVoT2pFbHMyc1hISXQ3eDNHZzlCVXNhZ0NJaExFQjJWQVczVFZCVVZCTGpBY25ZMmwKMTBxMUhhQ2hLd2lqM01lUWVzTFEvbTdhLytNTU9ob3dRMExJSENkRE5nOTNvZWVtM3FsZmx3bFFLNzlzSitTRQpRbG5BSlVBam1rZ3IKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
        service:
          namespace: openfunction
          name: webhook-service
          path: /convert
#        url: "https://<node-ip>:9443/convert"
      conversionReviewVersions:
      - v1
